### ISSUE TITLE
v3.5.14m11 has no xpi file hence autoupdate fails

### ISSUE THREAD

**Issue by duncdrum** [Juris-M/jurism-word-for-mac-integration#1]
latest release is missing compiled xpi file, hence auto-update fails on FF

**Comment by duncdrum** [comment]
@fbennett could you take a look and upload binaries?

**Comment by fbennett** [comment]
Should have beathing space for testing and uploads tomorrow.

**Comment by streinz** [comment]
The xpi file still seems to be missing.

**Comment by duncdrum** [comment]
Jurism now uses Zotero plugins and these are up to date
